[package]
name = "alr-models"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
alr-core = { workspace = true }
alr-execution = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
parking_lot = "0.12"
sha2 = "0.10"
hex = "0.4"
rand = { workspace = true }
