[package]
name = "alr-perception"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
alr-core = { workspace = true }
alr-world = { workspace = true }
alr-execution = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
image = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
